### ISSUE TITLE
Logging in astra-cli should use org.apache.log4j.Logger

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#1]
Currently, the logging in `astra-cli` uses `System.out.println`. This should be updated to match the approach in `astra-core`, where we use `org.apache.log4j.Logger`.

An example of our logging in `astra-core` can be seen in the [TypeReferenceRefactor](https://github.com/alfasoftware/astra/blob/main/astra-core/src/main/java/org/alfasoftware/astra/core/refactoring/operations/types/TypeReferenceRefactor.java) 

The logging that needs to be updated to match is in:
- [AstraChangeType](https://github.com/alfasoftware/astra/blob/main/astra-cli/src/main/java/org/alfasoftware/astracli/commandline/AstraChangeType.java)
- [AstraMethodInvocation](https://github.com/alfasoftware/astra/blob/main/astra-cli/src/main/java/org/alfasoftware/astracli/commandline/AstraMethodInvocation.java)

**Comment by AlexS968** [comment]
i would like to work on this

**Comment by RadikalJin** [comment]
Hi, thanks for your interest in Astra!

That would be great! Please take a look at our contribution policy, and
raise a pull request:
https://github.com/alfasoftware/astra/blob/main/CONTRIBUTING.md

**Comment by RadikalJin** [comment]
This has now been fixed by pull request #6. Thank you @AlexS968!

Closing the issue now.
