### ISSUE TITLE
Reduce cognitive complexity of ChainedMethodInvocationRefactor#handleMethodInvocation and use only one break or continue statement

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#104]
See https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=alfasoftware_astra&open=AYDiEpr_kKZeZDp5nkOu
and https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=alfasoftware_astra&open=AYDiEpr_kKZeZDp5nkOt

**Comment by mohannaidu** [comment]
can you assign this issue to me? let me have a go at it

**Comment by mohannaidu** [comment]
i managed to fix the first issue. looking at the second sonar issue

**Comment by RadikalJin** [comment]
Hey @mohannaidu! Sure, I’ll assign this to you now.

**Comment by mohannaidu** [comment]
Create a PR. Please review and let me know if any changes required.
