### ISSUE TITLE
Improvement: provide a maven plugin that can be used to run an Astra use-case on a maven-project

### ISSUE THREAD

**Issue by harrisric** [alfasoftware/astra#120]
In order to make it easier for users to benefit from Astra it would be useful to provide a simple plugin that would be able to refactor the source of the module(s) that it is applied to.

**Comment by harrisric** [comment]
Would also be good to create a new release (2.4.0) with this feature.

**Comment by RadikalJin** [comment]
@harrisric - I'll aim to get this released this week.

**Comment by RadikalJin** [comment]
This has now been completed and included with the newest releases of Astra. Thanks again, @harrisric.
