### ISSUE TITLE
Improve type matching for types with a parameterized super type

### ISSUE THREAD

**Issue by HatthewMarris** [alfasoftware/astra#21]
**Describe the bug**
When attempting to match a type where the super type is a parameterized type the fully qualified name of both the super type and type parameter must be given in order to ensure a match. We cannot currently easily match all sub-types of a parameterized  type regardless of the specific type parameter.

**To Reproduce**
1. Create a type matcher for a class that extends a parameterized type
2. Specify the fully qualified name of the parameterized super class as the TypeMatcher.superClass without the type parameter
3. Attempt to match the type declaration for the sub-class
4. The type matcher will not match the sub-class without having specified a type parameter for the super class

**Expected behavior**
TypeMatcher should be able to match either a sub-type of a parameterized type that takes a specific type parameter or any sub type of a parameterized type regardless of the specific type parameter.

```
 @Test
  public void testParameterizedTypeWithoutTypeParameterSpecified() {
    // Given
    String extendsMatcher = "package x;\r\n" +
        "import java.util.List;\r\n" +
        "public class y extends List<Integer>{}";
    
    Matcher parameterizedTypeMatcher = TypeMatcher.builder()
        .extending("java.util.List")
        .build();
  
    // When
    ClassVisitor visitor = parse(extendsMatcher);
  
    // Then
    List<TypeDeclaration> typeDeclarations = visitor.getTypeDeclarations();
    assertTrue(parameterizedTypeMatcher.matches(typeDeclarations.get(0)));
  }
  
  
  @Test
  public void testParameterizedTypeWithTypeParameterSpecified() {
    // Given
    String extendsMatcher = "package x;\r\n" +
        "import java.util.List;\r\n" +
        "public class y extends List<Integer>{}";
    
    Matcher parameterizedTypeMatcher = TypeMatcher.builder()
        .extending("java.util.List<java.lang.Integer>")
        .build();
  
    Matcher incorrectParameterizedTypeMatcher = TypeMatcher.builder()
        .extending("java.util.List<java.lang.Long>")
        .build();
    
    // When
    ClassVisitor visitor = parse(extendsMatcher);
    
    // Then
    List<TypeDeclaration> typeDeclarations = visitor.getTypeDeclarations();
    assertTrue(parameterizedTypeMatcher.matches(typeDeclarations.get(0)));
    assertFalse(incorrectParameterizedTypeMatcher.matches(typeDeclarations.get(0)));
  }
```

**Comment by RadikalJin** [comment]
This has now been fixed by @HatthewMarris under #21. Closing this issue now
