### ISSUE TITLE
TypeReferenceRefactor does not properly handle fully qualified names in Javadoc links

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#3]
A `TypeReferenceRefactor` from `org.alfasoftware.astra.exampleTypes.A` to `org.alfasoftware.astra.exampleTypes.B` should update all references. Currently, only simple type name references in Javadoc @link tags are updated. It should also cover fully qualified references, as in this example:
<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>
      <pre>
/**
 * {@link <b>org.alfasoftware.astra.exampleTypes.A</b>}
 */
public class Example {
}</pre>
    </td>
    <td>
      <pre>
/**
 * {@link <b>org.alfasoftware.astra.exampleTypes.B</b>}
 */
public class Example {
}</pre>
    </td>
  </tr>
</table>

A fully qualified import like this should be added to `TypeReferenceExample` and `TypeReferenceExampleAfter`, the examples used for `TestTypeReferenceRefactor#testChangeTypes`.

It's likely that there is a mistake in the `TypeReferenceRefactor` at around [line 117](https://github.com/alfasoftware/astra/blob/main/astra-core/src/main/java/org/alfasoftware/astra/core/refactoring/operations/types/TypeReferenceRefactor.java#L177), debugging at this point while running the test will likely show why we don't reach this block.

**Comment by 10wonga** [comment]
link in issue leads to line 177, not 117 which is an empty line. Will assume this refers to line 177.

**Comment by RadikalJin** [comment]
Fixed by @10wonga in #57.
