### ISSUE TITLE
Add tests for MethodMatcher matching on return type

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#4]
The `MethodMatcher` provides the [option to match by return type](https://github.com/alfasoftware/astra/blob/main/astra-core/src/main/java/org/alfasoftware/astra/core/matchers/MethodMatcher.java#L121). This isn't currently unit tested - coverage for this feature should be added to `TestMethodMatcher`.

**Comment by SivaTharun** [comment]
@RadikalJin i am newbie to open source contribution, can i start working on this issue.

**Comment by RadikalJin** [comment]
Hello @SivaTharun - and thank you for your interest in Astra!

That would be great. Our [contribution policy](https://github.com/alfasoftware/astra/blob/main/CONTRIBUTING.md) has a couple of tips for getting started.

**Comment by SivaTharun** [comment]
Thanks @RadikalJin for the info on contribution guidelines

**Comment by RadikalJin** [comment]
Hello @vihaannnn - that would be great! Our contribution policy has a couple of tips for getting started - thank you for your interest in Astra.

**Comment by vihaannnn** [comment]
@RadikalJin Thank You! As it is my first time contributing I am not sure how to run this codebase too see if what I will do works... could you help me out there?

**Comment by RadikalJin** [comment]
Fixed by #55
