### ISSUE TITLE
Add test for adding marker annotation in TestAnnotationsRefactor

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#60]
TestAnnotationsRefactor already includes a test for adding a single member annotation. This should also include a test for adding a marker annotation. This should be similar to the existing testAddAnnotation, but without adding the member.

**Comment by rhit-namburs** [comment]
I would like to work on this issue!

**Comment by RadikalJin** [comment]
Hello @rhit-namburs - you’d be welcome to!

**Comment by manpreet26git** [comment]
Hi, I would like to work on this issue

**Comment by RadikalJin** [comment]
Hello @manpreet26git - please feel free to. Thanks!
