### ISSUE TITLE
Add test coverage for FindMethodInvocationsAnalysis and FindMethodDeclarationsAnalysis

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#62]
Test coverage should be added for these analysis operations using the AbstractAnalysisTest framework.
The existing TestAssignmentAnalysis can be used as a model.

**Comment by ade3p** [comment]
:wave: Hi, is this issue still of significance considering was opened a year ago - if its still of interest and not being worked upon by anyone, I can take a look into it.

**Comment by RadikalJin** [comment]
Hi @ade3p - if you are happy to take a look that would be excellent, thanks!

**Comment by ade3p** [comment]
Hi @RadikalJin, created a draft PR #111 - kept it in a draft cuz made some modifications to existing code. Please review it.
