### ISSUE TITLE
Test failure due to variable name mismatch in InvocationChanedWrapped test case of MethodInvocationRefactor

### ISSUE THREAD

**Issue by monjurmorshed793** [alfasoftware/astra#69]
**Describe the bug**
In *InvocationChainedWrappedExample*, variable name for type of *A* is *wrappedA*. In the *InvocationChangedWrappedExampleAfter*, variable name is changed to *wrappedB*.  *MethodInvocationRefactor* currently changes the *method-type*, but doesn't rename the variable. As a result, *testInvocationChainedWrapped()* test fails. 

The issue is related to *TypeReferanceRefactor*. In *updateSimpleName(CompilationUnit compilationUnit, SimpleName name, ASTRewrite rewriter)* method,  in the *else if* condition  we have a condition *((IVariableBinding) binding).getType().getQualifiedName().contains(getFromType())* which returns false if the variable name has *Optional* with it.
So, *Optional* is needed to be removed from the *qualifiedName()*.

**Comment by monjurmorshed793** [comment]
Request for reviewing pull request #70 for resolving the issue.

**Comment by monjurmorshed793** [comment]
Actually, the issue is related to *TypeReferanceRefactor*. In *updateSimpleName(CompilationUnit compilationUnit, SimpleName name, ASTRewrite rewriter)* method,  in the *else if* condition  we have a condition *((IVariableBinding) binding).getType().getQualifiedName().contains(getFromType())* which returns false if the variable name has *Optional* with it.
So, if we replace the *equals* with "contains", then  the issue can be resolved.

**Comment by RadikalJin** [comment]
Hello @monjurmorshed793 - thank you for raising this issue, and for including a pull request fix.

---

This definitely works for Optionals with a matched type parameter. We might also want to cover other parameterized (described as "wrapped" in the test name) types, like these:

```
import java.util.function.Supplier;
import com.google.inject.Provider;

Supplier<A> wrappedA2 = () -> new A();
Provider<A> wrappedA3 = Providers.of(new A());
```

I attempted to handle this with the below, but while investigating it became apparent that the feature itself has a more serious issue.

<details>
  <summary>Here's the attempted fix - handling any parameterized type.</summary>
  
```
private void updateSimpleName(CompilationUnit compilationUnit, SimpleName name, ASTRewrite rewriter) {
  IBinding binding = name.resolveBinding();
  if (binding != null) {
    if (binding instanceof ITypeBinding && ((ITypeBinding) binding).getQualifiedName().equals(getFromType())) {
      log.info("Refactoring simple type [" + name.toString() + "] to [" + AstraUtils.getSimpleName(toType) + "] in [" +
      AstraUtils.getNameForCompilationUnit(compilationUnit) + "]");
      rewriter.set(name, SimpleName.IDENTIFIER_PROPERTY, AstraUtils.getSimpleName(toType), null);
    } else if (newVariableName != null && 
        binding instanceof IVariableBinding &&
      	isVariableBindingTypeMatch((IVariableBinding) binding, getFromType()) ||
        isParameterizedVariableBindingTypeMatch((IVariableBinding) binding, getFromType())) {
      log.info("Refactoring variable name [" + name.toString() + "] to [" + newVariableName + "] in [" +
      AstraUtils.getNameForCompilationUnit(compilationUnit) + "]");
      rewriter.set(name, SimpleName.IDENTIFIER_PROPERTY, newVariableName, null);
    }
  }
}

private boolean isVariableBindingTypeMatch(IVariableBinding iVariableBinding, String typeToMatch) {
  return iVariableBinding.getType().getQualifiedName().equals(typeToMatch);
}

private boolean isParameterizedVariableBindingTypeMatch(IVariableBinding iVariableBinding, String typeToMatch) {
  return iVariableBinding.getType().isParameterizedType() &&
    iVariableBinding.getType().getTypeArguments().length == 1 &&
    iVariableBinding.getType().getTypeArguments()[0].getQualifiedName().equals(typeToMatch);
}
```

This would handle the above two examples but also any other parameterized variable of the matched type, including ones that we might not want to rename - such as a Collection of that type:
`List<A> wrappedA3 = new ArrayList<>();`
It probably wouldn't make sense to rename variables like this in the same way as the cases above.

</details>

---

Here's the issue with the feature itself:
```
  Optional<A> wrappedA1 = Optional.of(new A());
  Optional<A> wrappedA4 = Optional.of(new A());
```
Here, both variables are matched and updated - but both will then have the same name. The "After" file would have multiple variables named `wrappedC`, which won't compile:
`Duplicate field InvocationChainedWrappedExampleAfter.wrappedC`

This isn't just a problem with parameterized type variable renames - this is a general problem with any variable renaming. Where there are multiple variables of the same type, the variable rename feature could produce code that won't compile.

This feature was added in the experimental early versions of Astra. To simplify the operation and remove a potential source of compilation failures, we will deprecate and remove it in future releases. Thank you for helping bring attention to this, @monjurmorshed793!

**Comment by RadikalJin** [comment]
Closing as this feature has now been removed under #71.
