### ISSUE TITLE
TypeMatcher: Replace type specification in constructor call with diamond operator ("<>")

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#86]
See 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=alfasoftware_astra&open=AX7Ef4REnKnktdNp7Qvi

**Comment by shyamrox** [comment]
I'll take this one.

**Comment by shyamrox** [comment]
Submitted Pull Request - https://github.com/alfasoftware/astra/pull/91

**Comment by RadikalJin** [comment]
Fixed by #91
