### ISSUE TITLE
Reduce cognitive complexity of InlineInterfaceRefactor#run

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#87]
See
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=alfasoftware_astra&open=AXhfYNg-01lXSQw-3UcP

**Comment by kapilgahlot1998** [comment]
Hi .. Can you please assign me this issue.

**Comment by rossilor95** [comment]
Hi! Can I work on this issue?

**Comment by craftyshark** [comment]
Hi, 

Does this issue still need help, or has it been handled? I noticed a pull request was merged but the issue was still opened. Wanted to ask first.

**Comment by RadikalJin** [comment]
Hi @craftyshark, thank you for checking (and for the nudge!) this should have been closed following the PR. I'll close it off now.
