### ISSUE TITLE
Reduce cognitive complexity of AstraUtils#getFullyQualifiedName

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#88]
See https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=alfasoftware_astra&open=AXpYXsQlw7HmrLPw-qnT

**Comment by kapilgahlot1998** [comment]
Hi .. can you please assign me this issue.

**Comment by RadikalJin** [comment]
Hello @kapilgahlot1998,

Sure! Thanks for your interest in contributing to Astra. I'll assign this over to you now.

**Comment by kapilgahlot1998** [comment]
Hi @RadikalJin .. I have fixed the code also build the service. But I didn't find any test case for this **AstraUtils#getFullyQualifiedName**. Can you please provide me some test cases details that I can cover in the test cases. 

Let me know if anything else required from myside

**Comment by RadikalJin** [comment]
Hello @kapilgahlot1998, that sounds good! There aren’t specific tests for that function but it’s used very widely across all the tests. If you’re able to run the full set of tests, that should give us the coverage needed to verify the change. If you raise a pull request, we can also run a branch build.

**Comment by kapilgahlot1998** [comment]
@RadikalJin  Yes, I have run a full build that is success. Let me create a PR. Thanks

**Comment by kapilgahlot1998** [comment]
@RadikalJin  Created PR for the same. Please review and let me know if any changes required in the code I will happy to do that.
Thanks

**Comment by RadikalJin** [comment]
Fixed by @kapilgahlot1998 under #93
