### ISSUE TITLE
Add coverage information with sonar

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#90]
Astra uses sonar for automated code quality scanning. The coverage feature is not currently configured, so shows 0% coverage. This should be enabled.
See https://sonarcloud.io/summary/overall?id=alfasoftware_astra

**Comment by ade3p** [comment]
<p>:wave: Hi, opened PR #110 covering possible fix for this issue - please check it out</p>

**Comment by RadikalJin** [comment]
This worked perfectly - coverage information is now showing correctly in sonarcloud.
https://sonarcloud.io/component_measures?id=alfasoftware_astra&metric=coverage&view=list
Thanks again, @ade3p!
